package shared.definitions;

public enum TurnState
{
	WAITING_FOR_PLAYERS, WAITING, PLAYING, ROBBING, ROLLING, DISCARDING, DISCARDED_CLOSING, DISCARDED_WAITING, DOMESTIC_TRADE, OFFERED_TRADE, MARITIME_TRADE, PLACING_PIECE,
		FIRST_ROUND_MY_TURN, FIRST_ROUND_WAITING, SECOND_ROUND_MY_TURN, SECOND_ROUND_WAITING, SOLIDER_CARD, ROAD_BUILDER, ROAD_BUILDER_SECOND, GAME_OVER();
}
